/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AppliedCouponObjectExtended;
import org.openapitools.client.model.PaginationMeta;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppliedCouponsPaginated
 */
public class AppliedCouponsPaginatedTest {
    private final AppliedCouponsPaginated model = new AppliedCouponsPaginated();

    /**
     * Model tests for AppliedCouponsPaginated
     */
    @Test
    public void testAppliedCouponsPaginated() {
        // TODO: test AppliedCouponsPaginated
    }

    /**
     * Test the property 'appliedCoupons'
     */
    @Test
    public void appliedCouponsTest() {
        // TODO: test appliedCoupons
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

}
