/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Country
 */
public class CountryTest {
    /**
     * Model tests for Country
     */
    @Test
    public void testCountry() {
        // TODO: test Country
    }

}
