/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.51.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CreditNoteEstimateInputCreditNote;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreditNoteEstimateInput
 */
public class CreditNoteEstimateInputTest {
    private final CreditNoteEstimateInput model = new CreditNoteEstimateInput();

    /**
     * Model tests for CreditNoteEstimateInput
     */
    @Test
    public void testCreditNoteEstimateInput() {
        // TODO: test CreditNoteEstimateInput
    }

    /**
     * Test the property 'creditNote'
     */
    @Test
    public void creditNoteTest() {
        // TODO: test creditNote
    }

}
