/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.51.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreditNoteEstimatedEstimatedCreditNoteItemsInner
 */
public class CreditNoteEstimatedEstimatedCreditNoteItemsInnerTest {
    private final CreditNoteEstimatedEstimatedCreditNoteItemsInner model = new CreditNoteEstimatedEstimatedCreditNoteItemsInner();

    /**
     * Model tests for CreditNoteEstimatedEstimatedCreditNoteItemsInner
     */
    @Test
    public void testCreditNoteEstimatedEstimatedCreditNoteItemsInner() {
        // TODO: test CreditNoteEstimatedEstimatedCreditNoteItemsInner
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    public void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'lagoFeeId'
     */
    @Test
    public void lagoFeeIdTest() {
        // TODO: test lagoFeeId
    }

}
