/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.52.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CustomerChargeUsageObjectCharge
 */
public class CustomerChargeUsageObjectChargeTest {
    private final CustomerChargeUsageObjectCharge model = new CustomerChargeUsageObjectCharge();

    /**
     * Model tests for CustomerChargeUsageObjectCharge
     */
    @Test
    public void testCustomerChargeUsageObjectCharge() {
        // TODO: test CustomerChargeUsageObjectCharge
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    public void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'chargeModel'
     */
    @Test
    public void chargeModelTest() {
        // TODO: test chargeModel
    }

    /**
     * Test the property 'invoiceDisplayName'
     */
    @Test
    public void invoiceDisplayNameTest() {
        // TODO: test invoiceDisplayName
    }

}
