/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.52.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FeeObjectAmountDetailsAllOfVolumeRangesInner
 */
public class FeeObjectAmountDetailsAllOfVolumeRangesInnerTest {
    private final FeeObjectAmountDetailsAllOfVolumeRangesInner model = new FeeObjectAmountDetailsAllOfVolumeRangesInner();

    /**
     * Model tests for FeeObjectAmountDetailsAllOfVolumeRangesInner
     */
    @Test
    public void testFeeObjectAmountDetailsAllOfVolumeRangesInner() {
        // TODO: test FeeObjectAmountDetailsAllOfVolumeRangesInner
    }

    /**
     * Test the property 'perUnitAmount'
     */
    @Test
    public void perUnitAmountTest() {
        // TODO: test perUnitAmount
    }

    /**
     * Test the property 'flatUnitAmount'
     */
    @Test
    public void flatUnitAmountTest() {
        // TODO: test flatUnitAmount
    }

    /**
     * Test the property 'perUnitTotalAmount'
     */
    @Test
    public void perUnitTotalAmountTest() {
        // TODO: test perUnitTotalAmount
    }

}
