/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.53.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FeeObjectAmountDetailsAllOfGraduatedPercentageRangesInner
 */
public class FeeObjectAmountDetailsAllOfGraduatedPercentageRangesInnerTest {
    private final FeeObjectAmountDetailsAllOfGraduatedPercentageRangesInner model = new FeeObjectAmountDetailsAllOfGraduatedPercentageRangesInner();

    /**
     * Model tests for FeeObjectAmountDetailsAllOfGraduatedPercentageRangesInner
     */
    @Test
    public void testFeeObjectAmountDetailsAllOfGraduatedPercentageRangesInner() {
        // TODO: test FeeObjectAmountDetailsAllOfGraduatedPercentageRangesInner
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'fromValue'
     */
    @Test
    public void fromValueTest() {
        // TODO: test fromValue
    }

    /**
     * Test the property 'toValue'
     */
    @Test
    public void toValueTest() {
        // TODO: test toValue
    }

    /**
     * Test the property 'flatUnitAmount'
     */
    @Test
    public void flatUnitAmountTest() {
        // TODO: test flatUnitAmount
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'perUnitTotalAmount'
     */
    @Test
    public void perUnitTotalAmountTest() {
        // TODO: test perUnitTotalAmount
    }

    /**
     * Test the property 'totalWithFlatAmount'
     */
    @Test
    public void totalWithFlatAmountTest() {
        // TODO: test totalWithFlatAmount
    }

}
