/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetCustomerPortalUrl200ResponseCustomer
 */
public class GetCustomerPortalUrl200ResponseCustomerTest {
    private final GetCustomerPortalUrl200ResponseCustomer model = new GetCustomerPortalUrl200ResponseCustomer();

    /**
     * Model tests for GetCustomerPortalUrl200ResponseCustomer
     */
    @Test
    public void testGetCustomerPortalUrl200ResponseCustomer() {
        // TODO: test GetCustomerPortalUrl200ResponseCustomer
    }

    /**
     * Test the property 'portalUrl'
     */
    @Test
    public void portalUrlTest() {
        // TODO: test portalUrl
    }

}
