/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetCustomerPortalUrl200ResponseCustomer;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GetCustomerPortalUrl200Response
 */
public class GetCustomerPortalUrl200ResponseTest {
    private final GetCustomerPortalUrl200Response model = new GetCustomerPortalUrl200Response();

    /**
     * Model tests for GetCustomerPortalUrl200Response
     */
    @Test
    public void testGetCustomerPortalUrl200Response() {
        // TODO: test GetCustomerPortalUrl200Response
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

}
