/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.51.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GrossRevenueObject;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GrossRevenues
 */
public class GrossRevenuesTest {
    private final GrossRevenues model = new GrossRevenues();

    /**
     * Model tests for GrossRevenues
     */
    @Test
    public void testGrossRevenues() {
        // TODO: test GrossRevenues
    }

    /**
     * Test the property 'grossRevenues'
     */
    @Test
    public void grossRevenuesTest() {
        // TODO: test grossRevenues
    }

}
