/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.52.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.InvoiceOneOffCreateInputInvoiceFeesInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for InvoiceOneOffCreateInputInvoice
 */
public class InvoiceOneOffCreateInputInvoiceTest {
    private final InvoiceOneOffCreateInputInvoice model = new InvoiceOneOffCreateInputInvoice();

    /**
     * Model tests for InvoiceOneOffCreateInputInvoice
     */
    @Test
    public void testInvoiceOneOffCreateInputInvoice() {
        // TODO: test InvoiceOneOffCreateInputInvoice
    }

    /**
     * Test the property 'externalCustomerId'
     */
    @Test
    public void externalCustomerIdTest() {
        // TODO: test externalCustomerId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

}
