/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.52.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for InvoiceOneOffCreateInputInvoiceFeesInner
 */
public class InvoiceOneOffCreateInputInvoiceFeesInnerTest {
    private final InvoiceOneOffCreateInputInvoiceFeesInner model = new InvoiceOneOffCreateInputInvoiceFeesInner();

    /**
     * Model tests for InvoiceOneOffCreateInputInvoiceFeesInner
     */
    @Test
    public void testInvoiceOneOffCreateInputInvoiceFeesInner() {
        // TODO: test InvoiceOneOffCreateInputInvoiceFeesInner
    }

    /**
     * Test the property 'addOnCode'
     */
    @Test
    public void addOnCodeTest() {
        // TODO: test addOnCode
    }

    /**
     * Test the property 'invoiceDisplayName'
     */
    @Test
    public void invoiceDisplayNameTest() {
        // TODO: test invoiceDisplayName
    }

    /**
     * Test the property 'unitAmountCents'
     */
    @Test
    public void unitAmountCentsTest() {
        // TODO: test unitAmountCents
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'taxCodes'
     */
    @Test
    public void taxCodesTest() {
        // TODO: test taxCodes
    }

}
