/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.ChargeObject;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.TaxObject;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PlanObject
 */
public class PlanObjectTest {
    private final PlanObject model = new PlanObject();

    /**
     * Model tests for PlanObject
     */
    @Test
    public void testPlanObject() {
        // TODO: test PlanObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    public void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    public void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    public void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    public void trialPeriodTest() {
        // TODO: test trialPeriod
    }

    /**
     * Test the property 'payInAdvance'
     */
    @Test
    public void payInAdvanceTest() {
        // TODO: test payInAdvance
    }

    /**
     * Test the property 'billChargesMonthly'
     */
    @Test
    public void billChargesMonthlyTest() {
        // TODO: test billChargesMonthly
    }

    /**
     * Test the property 'activeSubscriptionsCount'
     */
    @Test
    public void activeSubscriptionsCountTest() {
        // TODO: test activeSubscriptionsCount
    }

    /**
     * Test the property 'draftInvoicesCount'
     */
    @Test
    public void draftInvoicesCountTest() {
        // TODO: test draftInvoicesCount
    }

    /**
     * Test the property 'charges'
     */
    @Test
    public void chargesTest() {
        // TODO: test charges
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

}
