/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PlanInputPlanChargesInnerGroupPropertiesInner
 */
public class PlanInputPlanChargesInnerGroupPropertiesInnerTest {
    private final PlanInputPlanChargesInnerGroupPropertiesInner model = new PlanInputPlanChargesInnerGroupPropertiesInner();

    /**
     * Model tests for PlanInputPlanChargesInnerGroupPropertiesInner
     */
    @Test
    public void testPlanInputPlanChargesInnerGroupPropertiesInner() {
        // TODO: test PlanInputPlanChargesInnerGroupPropertiesInner
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
