/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.52.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.PlanOverridesObjectChargesInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PlanOverridesObject
 */
public class PlanOverridesObjectTest {
    private final PlanOverridesObject model = new PlanOverridesObject();

    /**
     * Model tests for PlanOverridesObject
     */
    @Test
    public void testPlanOverridesObject() {
        // TODO: test PlanOverridesObject
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    public void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    public void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'invoiceDisplayName'
     */
    @Test
    public void invoiceDisplayNameTest() {
        // TODO: test invoiceDisplayName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'taxCodes'
     */
    @Test
    public void taxCodesTest() {
        // TODO: test taxCodes
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    public void trialPeriodTest() {
        // TODO: test trialPeriod
    }

    /**
     * Test the property 'charges'
     */
    @Test
    public void chargesTest() {
        // TODO: test charges
    }

}
