/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.PlanCreateInputPlanChargesInner;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PlanCreateInputPlan
 */
public class PlanCreateInputPlanTest {
    private final PlanCreateInputPlan model = new PlanCreateInputPlan();

    /**
     * Model tests for PlanCreateInputPlan
     */
    @Test
    public void testPlanCreateInputPlan() {
        // TODO: test PlanCreateInputPlan
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    public void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    public void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    public void trialPeriodTest() {
        // TODO: test trialPeriod
    }

    /**
     * Test the property 'payInAdvance'
     */
    @Test
    public void payInAdvanceTest() {
        // TODO: test payInAdvance
    }

    /**
     * Test the property 'billChargesMonthly'
     */
    @Test
    public void billChargesMonthlyTest() {
        // TODO: test billChargesMonthly
    }

    /**
     * Test the property 'taxCodes'
     */
    @Test
    public void taxCodesTest() {
        // TODO: test taxCodes
    }

    /**
     * Test the property 'charges'
     */
    @Test
    public void chargesTest() {
        // TODO: test charges
    }

}
