/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PaginationMeta;
import org.openapitools.client.model.WalletTransactionObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WalletTransactionsPaginated
 */
public class WalletTransactionsPaginatedTest {
    private final WalletTransactionsPaginated model = new WalletTransactionsPaginated();

    /**
     * Model tests for WalletTransactionsPaginated
     */
    @Test
    public void testWalletTransactionsPaginated() {
        // TODO: test WalletTransactionsPaginated
    }

    /**
     * Test the property 'walletTransactions'
     */
    @Test
    public void walletTransactionsTest() {
        // TODO: test walletTransactions
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

}
