/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.52.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.AppliedCouponObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AppliedCoupon
 */
@JsonPropertyOrder({
  AppliedCoupon.JSON_PROPERTY_APPLIED_COUPON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-24T14:46:07.416771019Z[Etc/UTC]")
public class AppliedCoupon {
  public static final String JSON_PROPERTY_APPLIED_COUPON = "applied_coupon";
  private AppliedCouponObject appliedCoupon;

  public AppliedCoupon() {
  }

  public AppliedCoupon appliedCoupon(AppliedCouponObject appliedCoupon) {
    
    this.appliedCoupon = appliedCoupon;
    return this;
  }

   /**
   * Get appliedCoupon
   * @return appliedCoupon
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLIED_COUPON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AppliedCouponObject getAppliedCoupon() {
    return appliedCoupon;
  }


  @JsonProperty(JSON_PROPERTY_APPLIED_COUPON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppliedCoupon(AppliedCouponObject appliedCoupon) {
    this.appliedCoupon = appliedCoupon;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppliedCoupon appliedCoupon = (AppliedCoupon) o;
    return Objects.equals(this.appliedCoupon, appliedCoupon.appliedCoupon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appliedCoupon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppliedCoupon {\n");
    sb.append("    appliedCoupon: ").append(toIndentedString(appliedCoupon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

