/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.AppliedAddOnObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AppliedAddOn
 */
@JsonPropertyOrder({
  AppliedAddOn.JSON_PROPERTY_APPLIED_ADD_ON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-31T15:04:44.084574Z[Etc/UTC]")
public class AppliedAddOn {
  public static final String JSON_PROPERTY_APPLIED_ADD_ON = "applied_add_on";
  private AppliedAddOnObject appliedAddOn;

  public AppliedAddOn() {
  }

  public AppliedAddOn appliedAddOn(AppliedAddOnObject appliedAddOn) {
    
    this.appliedAddOn = appliedAddOn;
    return this;
  }

   /**
   * Get appliedAddOn
   * @return appliedAddOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLIED_ADD_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AppliedAddOnObject getAppliedAddOn() {
    return appliedAddOn;
  }


  @JsonProperty(JSON_PROPERTY_APPLIED_ADD_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppliedAddOn(AppliedAddOnObject appliedAddOn) {
    this.appliedAddOn = appliedAddOn;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppliedAddOn appliedAddOn = (AppliedAddOn) o;
    return Objects.equals(this.appliedAddOn, appliedAddOn.appliedAddOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appliedAddOn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppliedAddOn {\n");
    sb.append("    appliedAddOn: ").append(toIndentedString(appliedAddOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

