/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.46.0-beta
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.BillableMetricObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BillableMetric
 */
@JsonPropertyOrder({
  BillableMetric.JSON_PROPERTY_BILLABLE_METRIC
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-31T15:04:44.084574Z[Etc/UTC]")
public class BillableMetric {
  public static final String JSON_PROPERTY_BILLABLE_METRIC = "billable_metric";
  private BillableMetricObject billableMetric;

  public BillableMetric() {
  }

  public BillableMetric billableMetric(BillableMetricObject billableMetric) {
    
    this.billableMetric = billableMetric;
    return this;
  }

   /**
   * Get billableMetric
   * @return billableMetric
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BILLABLE_METRIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BillableMetricObject getBillableMetric() {
    return billableMetric;
  }


  @JsonProperty(JSON_PROPERTY_BILLABLE_METRIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBillableMetric(BillableMetricObject billableMetric) {
    this.billableMetric = billableMetric;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillableMetric billableMetric = (BillableMetric) o;
    return Objects.equals(this.billableMetric, billableMetric.billableMetric);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billableMetric);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillableMetric {\n");
    sb.append("    billableMetric: ").append(toIndentedString(billableMetric)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

